{
 "title": "Sentinel-Dashboard",
 "description": "traefik & prometheus",
 "tags": [
  "traefik",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "query": "label_values(service)" },
   { "name": "entrypoint", "query": "label_values(entrypoint)" },
   { "name": "code", "query": "label_values(code)" }
  ]
 },
 "panels": [
  { "title": "$service stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests $service (5m)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 1, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{service=\"$service\"}[5m]))",
     "legendFormat": "{{$service}} | {{method}}"
    }
   ]
  },
  {
   "title": "Average Response Time $service (5m)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(traefik_service_request_duration_seconds_sum{service=\"$service\"})",
     "legendFormat": "{{service}} | {{method}}"
    }
   ]
  },
  {
   "title": "Status Code Rate (last 5 minutes)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_service_requests_total{service=\"$service\"}[5m]) * 100",
     "legendFormat": "{{ method }} : {{code}}"
    }
   ]
  },
  {
   "title": "Status Code Totals (last hour)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{service=\"$service\"}[1h])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  }
 ]
}