apiVersion: 1
deleteDatasources:
  - name: Prometheus
    orgId: 1
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: traefik_prometheus:9090
  password:
  user:
  database:
  basicAuth: false
  basicAuthUser: admin
  basicAuthPassword: foobar
  withCredentials:
  isDefault: true
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
     tlsSkipVerify: true
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
  version: 1
  editable: true