---
version: "3.7"

services:
  production:
    image: {{ productionImagePath }}
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: {{ '{{ scaleNumber }}' }}
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      labels:
        - traefik.enable=true
        - traefik.http.routers.{{ appName }}_production_rtr.rule=Host(`{{ hostname }}`)
        # - traefik.http.routers.{{ appName }}_production_rtr.entrypoints=web
        - traefik.http.routers.{{ appName }}_production_rtr.entrypoints=websecure
        - traefik.http.routers.{{ appName }}_production_rtr.tls=true
        - traefik.http.routers.{{ appName }}_production_rtr.tls.certresolver=myresolver
        # the port listed here MUST be the internal post listed in the image
        - traefik.http.services.{{ appName }}_production_svc.loadbalancer.server.port={{ productionPort }}

networks:
  traefik-public:
    driver: overlay
    attachable: true
    name: traefik-public
    external: true
