http:
  services:
    {{ appName }}_weighted_svc:
      weighted:
        services:
          - name: {{ appName }}_production_svc@docker
            weight: {{ productionWeight|default(2) }} # FIXME: CHANGE DEFAULT TO 95
          - name: {{ appName }}_canary_svc@docker
            weight: {{ canaryWeight|default(1) }} # FIXME: CHANGE DEFAULT TO 5