---
  - name: Create template for changing scale
    hosts: localhost
    connection: local
    tasks:
      - name: Create template
        template: src=../assets/template_production_no_db_scale.yml dest=../assets/template_{{ appName }}_production_set_scale.yml
        delegate_to: localhost
  - name: Transfer templates to the manager
    hosts: managers
    become: true
    tasks:
      - name: Populate production template and transfer to manager
        template:
          src: ../assets/template_production_no_db.yml
          dest: /{{ appName }}_production.yml
  - name: Deploy application 
    hosts: managers
    become: true
    tasks:
      - name: Deploy new service stack
        command: sudo docker stack deploy -c /{{ appName }}_production.yml "{{ appName }}"