---
- name: Transfer dynamic config to manager
  hosts: managers
  become: true
  tasks:
    - name: Populate dynamic config template and transfer
      template:
        src: ../assets/template_dynamic_config.yml
        dest: /conf.d/{{ appName }}_dynamic.yml
- name: Transfer templates to the manager
  hosts: managers
  become: true
  tasks:
    - name: Populate dual compose template and transfer
      template:
        src: ../assets/template_canary_no_db.yml
        dest: /{{ appName }}_canary.yml
    - name: Transfer new production template in case of rollback
      template:
        src: ../assets/template_production_no_db.yml
        dest: /{{ appName }}_production.yml
- name: Deploy application 
  hosts: managers
  become: true
  tasks:
    - name: Deploy new service stack
      command: sudo docker stack deploy -c /{{ appName }}_canary.yml "{{ appName }}"