---
  - name: Transfer a template to the manager
    hosts: managers
    become: true
    tasks:
      - name: Populate template and transfer to manager
        template:
          src: ../assets/template_db_sql.yml
          dest: /{{ appName }}_db.yml
  - name: Copy sql file to manager
    hosts: managers
    become: true
    tasks:
      - name: Copy sql init file to manager
        copy:
          src: ../assets/sql/{{appName}}_db.sql
          dest: /sql/{{appName}}_db.sql
  - name: Deploy database 
    hosts: managers
    become: true
    tasks:
      - name: Deploy database
        command: sudo docker stack deploy -c /{{ appName }}_db.yml "{{ appName }}"
  - name: Transfer app template to the manager
    hosts: managers
    become: true
    tasks:
      - name: Populate app with db template and transfer to manager
        template:
          src: ../assets/template_production_db.yml
          dest: /{{ appName }}_production.yml
  - name: Deploy application 
    hosts: managers
    become: true
    tasks:
      - name: Deploy new service stack
        command: sudo docker stack deploy -c /{{ appName }}_production.yml "{{ appName }}"