---
  - name: Create template for changing scale
    hosts: localhost
    connection: local
    tasks:
      - name: Create template
        template: src=../assets/template_production_db_scale.yml dest=../assets/template_{{ appName }}_production_set_scale.yml
        delegate_to: localhost
  - name: Transfer a template to the manager
    hosts: managers
    become: true
    tasks:
      - name: Populate db template and transfer to manager
        template:
          src: ../assets/template_db_nosql.yml
          dest: /{{ appName }}_db.yml
  - name: Deploy database 
    hosts: managers
    become: true
    tasks:
      - name: Deploy database
        command: sudo docker stack deploy -c /{{ appName }}_db.yml "{{ appName }}"
  - name: Transfer a template to the manager
    hosts: managers
    become: true
    tasks:
      - name: Populate app with db template and transfer to manager
        template:
          src: ../assets/template_production_db.yml
          dest: /{{ appName }}_production.yml
  - name: Deploy application 
    hosts: managers
    become: true
    tasks:
      - name: Deploy new service stack
        command: sudo docker stack deploy -c /{{ appName }}_production.yml "{{ appName }}"