---
- name: Get list of running apps
  hosts: managers
  become: true
  gather_facts: False
  tasks:
    - name: Get Running Apps
      command: "sudo docker service ls --format  '{{ '{{' }}json .Name{{ '}}' }}}}'"
      register: apps
    - name: Show Running Apps
      debug:
        msg: "apps.stout | to_json"
        # "{{apps.stdout | to_json}}"