############################################################################################
#                                                                                          #
#                                                                                          #
#                                           CAUTION!                                       #
#                                                                                          #
#                                                                                          #
#                                                                                          #
# THIS PLAYBOOK SHOULD NOT BE USED IT'S THE ORIGINAL ONE THAT HAS SINCE BEEN SECTIONED OFF #
# INTO IT'S OWN PIECES. IT SHOULD ONLY BE USED AS A REFERENCE AT THIS POINT AND PROBABLY   #
# SHOULD BE DELETED AT SOME TIME IN THE FUTURE                                             #
#                                                                                          #
#                                                                                          #
#                                                                                          #
############################################################################################
---
- name: Install Docker and Docker Compose
  hosts: all
  become: true
  gather_facts: False
  tasks:
    - name: Update yum package manager
      command: yum update -y
    - name: Install Docker
      command: yum install docker -y
    - name: Enable docker
      command: systemctl enable docker
    - name: Start docker
      command: systemctl start docker
    # this is a convienience for when we have to ssh into the nodes.
    - name: Add sudo permissions for default ec2-user with docker
      command: sudo usermod -aG docker ec2-user
- name: Init Swarm Manager
  hosts: managers
  become: true
  gather_facts: False
  tasks:
    - debug:
        var: "{{ hostvars[groups['managers'][0]].manager_private_ip }}"
    - name: Swarm Init
      command: docker swarm init --advertise-addr {{ hostvars[groups['managers'][0]].manager_private_ip }}
    - name: Get Worker Token
      command: docker swarm join-token worker -q
      register: worker_token
    - name: Show Worker Token
      debug: var=worker_token.stdout
    - name: Manager Token
      command: docker swarm join-token manager -q
      register: manager_token
    - name: Show Manager Token
      debug: var=manager_token.stdout
- name: Join Swarm Cluster
  hosts: workers
  become: true
  gather_facts: False
  vars:
    token: "{{ hostvars[groups['managers'][0]]['worker_token']['stdout'] }}"
    manager: "{{ hostvars[groups['managers'][0]].manager_private_ip }}"
  tasks:
    - name: Join Swarm Cluster as a Worker
      command: docker swarm join --token {{ token }} {{ manager }}:2377
      register: worker
    - name: Show Results
      debug: var=worker.stdout
    - name: Show Errors
      debug: var=worker.stderr
- name: Copy Docker Compose and Traefik config files
  hosts: managers
  become: true
  tasks:
    - name: Copy files
      copy:
        src: ../assets/
        dest: /
- name: Deploy stacks
  hosts: managers
  become: true
  tasks:
    - name: Deploy traefik stack
      command: sudo docker stack deploy -c /stack-traefik-main.yaml traefik
    - name: Deploy catnip stack
      command: sudo docker stack deploy -c /stack-canary.yaml catnip
