---
- name: Relaunch production stack to remove traffic splitting labels and remove canary service
  hosts: managers
  become: true
  tasks:
    - name: Run docker stack deploy
      command: docker stack deploy -c /{{ appName }}_production.yml "{{ appName }}"
- name: Promote Canary
  hosts: managers
  become: true
  tasks:
    - name: Run docker service update command
      command: docker service update --image {{ updateImage }} {{ appName }}_production
- name: Remove canary service
  hosts: managers
  become: true
  tasks:
    - name: Remove canary service
      command: docker service rm {{ appName }}_canary
- name: Remove dynamic config file
  hosts: managers
  become: true
  tasks:
    - name: Remove the dynamic config file
      file:
        path: /conf.d/{{ appName }}_dynamic.yml
        state: absent